create table professor (
	id_matricula INT,
	nota INT,
	formação VARCHAR(24)
);
insert into professor (id_matricula, nota, formação) values (1, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (2, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (3, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (4, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (5, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (6, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (7, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (8, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (9, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (10, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (11, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (12, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (13, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (14, 2, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (15, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (16, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (17, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (18, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (19, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (20, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (21, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (22, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (23, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (24, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (25, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (26, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (27, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (28, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (29, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (30, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (31, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (32, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (33, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (34, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (35, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (36, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (37, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (38, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (39, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (40, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (41, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (42, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (43, 2, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (44, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (45, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (46, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (47, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (48, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (49, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (50, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (51, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (52, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (53, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (54, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (55, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (56, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (57, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (58, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (59, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (60, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (61, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (62, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (63, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (64, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (65, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (66, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (67, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (68, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (69, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (70, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (71, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (72, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (73, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (74, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (75, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (76, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (77, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (78, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (79, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (80, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (81, 9, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (82, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (83, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (84, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (85, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (86, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (87, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (88, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (89, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (90, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (91, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (92, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (93, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (94, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (95, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (96, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (97, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (98, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (99, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (100, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (101, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (102, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (103, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (104, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (105, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (106, 2, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (107, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (108, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (109, 2, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (110, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (111, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (112, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (113, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (114, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (115, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (116, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (117, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (118, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (119, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (120, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (121, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (122, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (123, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (124, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (125, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (126, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (127, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (128, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (129, 2, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (130, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (131, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (132, 9, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (133, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (134, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (135, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (136, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (137, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (138, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (139, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (140, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (141, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (142, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (143, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (144, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (145, 2, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (146, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (147, 9, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (148, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (149, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (150, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (151, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (152, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (153, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (154, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (155, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (156, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (157, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (158, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (159, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (160, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (161, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (162, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (163, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (164, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (165, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (166, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (167, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (168, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (169, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (170, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (171, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (172, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (173, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (174, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (175, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (176, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (177, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (178, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (179, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (180, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (181, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (182, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (183, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (184, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (185, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (186, 2, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (187, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (188, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (189, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (190, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (191, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (192, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (193, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (194, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (195, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (196, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (197, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (198, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (199, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (200, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (201, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (202, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (203, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (204, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (205, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (206, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (207, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (208, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (209, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (210, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (211, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (212, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (213, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (214, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (215, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (216, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (217, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (218, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (219, 2, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (220, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (221, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (222, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (223, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (224, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (225, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (226, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (227, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (228, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (229, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (230, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (231, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (232, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (233, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (234, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (235, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (236, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (237, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (238, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (239, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (240, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (241, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (242, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (243, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (244, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (245, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (246, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (247, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (248, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (249, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (250, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (251, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (252, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (253, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (254, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (255, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (256, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (257, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (258, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (259, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (260, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (261, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (262, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (263, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (264, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (265, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (266, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (267, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (268, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (269, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (270, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (271, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (272, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (273, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (274, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (275, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (276, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (277, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (278, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (279, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (280, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (281, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (282, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (283, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (284, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (285, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (286, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (287, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (288, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (289, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (290, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (291, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (292, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (293, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (294, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (295, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (296, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (297, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (298, 9, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (299, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (300, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (301, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (302, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (303, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (304, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (305, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (306, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (307, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (308, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (309, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (310, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (311, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (312, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (313, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (314, 9, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (315, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (316, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (317, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (318, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (319, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (320, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (321, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (322, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (323, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (324, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (325, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (326, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (327, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (328, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (329, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (330, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (331, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (332, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (333, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (334, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (335, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (336, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (337, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (338, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (339, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (340, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (341, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (342, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (343, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (344, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (345, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (346, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (347, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (348, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (349, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (350, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (351, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (352, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (353, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (354, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (355, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (356, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (357, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (358, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (359, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (360, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (361, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (362, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (363, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (364, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (365, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (366, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (367, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (368, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (369, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (370, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (371, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (372, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (373, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (374, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (375, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (376, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (377, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (378, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (379, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (380, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (381, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (382, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (383, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (384, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (385, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (386, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (387, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (388, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (389, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (390, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (391, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (392, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (393, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (394, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (395, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (396, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (397, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (398, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (399, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (400, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (401, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (402, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (403, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (404, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (405, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (406, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (407, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (408, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (409, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (410, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (411, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (412, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (413, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (414, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (415, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (416, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (417, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (418, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (419, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (420, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (421, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (422, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (423, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (424, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (425, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (426, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (427, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (428, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (429, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (430, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (431, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (432, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (433, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (434, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (435, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (436, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (437, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (438, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (439, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (440, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (441, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (442, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (443, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (444, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (445, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (446, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (447, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (448, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (449, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (450, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (451, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (452, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (453, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (454, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (455, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (456, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (457, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (458, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (459, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (460, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (461, 2, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (462, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (463, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (464, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (465, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (466, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (467, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (468, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (469, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (470, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (471, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (472, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (473, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (474, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (475, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (476, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (477, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (478, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (479, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (480, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (481, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (482, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (483, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (484, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (485, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (486, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (487, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (488, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (489, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (490, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (491, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (492, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (493, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (494, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (495, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (496, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (497, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (498, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (499, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (500, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (501, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (502, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (503, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (504, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (505, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (506, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (507, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (508, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (509, 9, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (510, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (511, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (512, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (513, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (514, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (515, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (516, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (517, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (518, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (519, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (520, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (521, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (522, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (523, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (524, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (525, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (526, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (527, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (528, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (529, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (530, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (531, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (532, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (533, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (534, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (535, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (536, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (537, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (538, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (539, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (540, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (541, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (542, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (543, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (544, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (545, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (546, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (547, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (548, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (549, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (550, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (551, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (552, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (553, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (554, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (555, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (556, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (557, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (558, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (559, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (560, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (561, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (562, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (563, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (564, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (565, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (566, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (567, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (568, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (569, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (570, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (571, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (572, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (573, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (574, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (575, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (576, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (577, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (578, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (579, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (580, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (581, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (582, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (583, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (584, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (585, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (586, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (587, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (588, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (589, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (590, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (591, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (592, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (593, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (594, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (595, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (596, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (597, 9, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (598, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (599, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (600, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (601, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (602, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (603, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (604, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (605, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (606, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (607, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (608, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (609, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (610, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (611, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (612, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (613, 9, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (614, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (615, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (616, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (617, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (618, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (619, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (620, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (621, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (622, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (623, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (624, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (625, 2, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (626, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (627, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (628, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (629, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (630, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (631, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (632, 9, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (633, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (634, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (635, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (636, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (637, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (638, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (639, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (640, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (641, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (642, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (643, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (644, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (645, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (646, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (647, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (648, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (649, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (650, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (651, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (652, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (653, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (654, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (655, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (656, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (657, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (658, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (659, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (660, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (661, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (662, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (663, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (664, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (665, 2, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (666, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (667, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (668, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (669, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (670, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (671, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (672, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (673, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (674, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (675, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (676, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (677, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (678, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (679, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (680, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (681, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (682, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (683, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (684, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (685, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (686, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (687, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (688, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (689, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (690, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (691, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (692, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (693, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (694, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (695, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (696, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (697, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (698, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (699, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (700, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (701, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (702, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (703, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (704, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (705, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (706, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (707, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (708, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (709, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (710, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (711, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (712, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (713, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (714, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (715, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (716, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (717, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (718, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (719, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (720, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (721, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (722, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (723, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (724, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (725, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (726, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (727, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (728, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (729, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (730, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (731, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (732, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (733, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (734, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (735, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (736, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (737, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (738, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (739, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (740, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (741, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (742, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (743, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (744, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (745, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (746, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (747, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (748, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (749, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (750, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (751, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (752, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (753, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (754, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (755, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (756, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (757, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (758, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (759, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (760, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (761, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (762, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (763, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (764, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (765, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (766, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (767, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (768, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (769, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (770, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (771, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (772, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (773, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (774, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (775, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (776, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (777, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (778, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (779, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (780, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (781, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (782, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (783, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (784, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (785, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (786, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (787, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (788, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (789, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (790, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (791, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (792, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (793, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (794, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (795, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (796, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (797, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (798, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (799, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (800, 9, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (801, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (802, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (803, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (804, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (805, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (806, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (807, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (808, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (809, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (810, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (811, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (812, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (813, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (814, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (815, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (816, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (817, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (818, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (819, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (820, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (821, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (822, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (823, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (824, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (825, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (826, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (827, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (828, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (829, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (830, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (831, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (832, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (833, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (834, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (835, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (836, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (837, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (838, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (839, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (840, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (841, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (842, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (843, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (844, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (845, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (846, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (847, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (848, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (849, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (850, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (851, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (852, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (853, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (854, 2, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (855, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (856, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (857, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (858, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (859, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (860, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (861, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (862, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (863, 10, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (864, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (865, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (866, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (867, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (868, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (869, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (870, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (871, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (872, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (873, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (874, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (875, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (876, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (877, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (878, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (879, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (880, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (881, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (882, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (883, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (884, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (885, 5, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (886, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (887, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (888, 2, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (889, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (890, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (891, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (892, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (893, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (894, 5, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (895, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (896, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (897, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (898, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (899, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (900, 6, 'redes');
insert into professor (id_matricula, nota, formação) values (901, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (902, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (903, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (904, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (905, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (906, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (907, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (908, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (909, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (910, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (911, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (912, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (913, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (914, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (915, 9, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (916, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (917, 3, 'redes');
insert into professor (id_matricula, nota, formação) values (918, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (919, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (920, 9, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (921, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (922, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (923, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (924, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (925, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (926, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (927, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (928, 9, 'redes');
insert into professor (id_matricula, nota, formação) values (929, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (930, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (931, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (932, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (933, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (934, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (935, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (936, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (937, 4, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (938, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (939, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (940, 1, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (941, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (942, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (943, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (944, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (945, 7, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (946, 1, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (947, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (948, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (949, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (950, 9, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (951, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (952, 2, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (953, 9, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (954, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (955, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (956, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (957, 4, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (958, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (959, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (960, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (961, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (962, 2, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (963, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (964, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (965, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (966, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (967, 8, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (968, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (969, 2, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (970, 6, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (971, 7, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (972, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (973, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (974, 5, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (975, 1, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (976, 10, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (977, 3, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (978, 2, 'redes');
insert into professor (id_matricula, nota, formação) values (979, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (980, 8, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (981, 6, 'sistemas de informaçao');
insert into professor (id_matricula, nota, formação) values (982, 3, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (983, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (984, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (985, 9, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (986, 3, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (987, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (988, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (989, 4, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (990, 4, 'redes');
insert into professor (id_matricula, nota, formação) values (991, 10, 'redes');
insert into professor (id_matricula, nota, formação) values (992, 8, 'redes');
insert into professor (id_matricula, nota, formação) values (993, 10, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (994, 6, 'engenharia de computaçao');
insert into professor (id_matricula, nota, formação) values (995, 7, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (996, 7, 'redes');
insert into professor (id_matricula, nota, formação) values (997, 1, 'redes');
insert into professor (id_matricula, nota, formação) values (998, 8, 'ciencia da computaçao');
insert into professor (id_matricula, nota, formação) values (999, 5, 'redes');
insert into professor (id_matricula, nota, formação) values (1000, 10, 'ciencia da computaçao');
